### ISSUE TITLE
[INCOMPATIBLE with Android Q and up] --> Firebase Job Dispatcher

### ISSUE THREAD

**Issue by murageden** [aritraroy/UltimateAndroidReference#102]
Please, correct information on this library:
https://github.com/firebase/firebase-jobdispatcher-android

that it will NOT BE COMPATIBLE with apps targeting releases beyond Android Q.
that we should look into using the [Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/) apis (still in alpha), instead.

thanks

**Comment by aritraroy** [comment]
Removed this library from this list. Thanks for pointing this out.
