### ISSUE TITLE
Add AndroidUtilCode in Utilities?

### ISSUE THREAD

**Issue by Blankj** [aritraroy/UltimateAndroidReference#27]
[AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode): A collection of util in Android and 
it is updating.

**Comment by aritraroy** [comment]
This is really nice. Would you like to raise a Pull Request for this? I would love to include it on this list. :-)

**Comment by Blankj** [comment]
yeah :-)

**Comment by ForgetAll** [comment]
lol, i think AndroidUtilCode is a good project~

**Comment by aritraroy** [comment]
I have merged your PR. Thank you for your contribution. 👍
