### ISSUE TITLE
Is it a map or random reference?

### ISSUE THREAD

**Issue by owususamuel** [aritraroy/UltimateAndroidReference#53]
It would be better for beginners if you could arrange it linearly like a **road map** to follow.
I know they are very good resources but which one do I start with?
Something like the "road map to web development 2017" will be very nice.

**Comment by aritraroy** [comment]
This is a good suggestion. But currently, it is a compilation of some of the best resources. I will surely consider creating a road map styled resource soon.

**Comment by owususamuel** [comment]
I will surely love that. thanks
