### ISSUE TITLE
Suggestion for site: Android Design Patterns

### ISSUE THREAD

**Issue by alexjlockwood** [aritraroy/UltimateAndroidReference#6]
Disclaimer: I am the maintainer of this blog. :)

Feel free to add if you want (you don't have to either though :P).

http://www.androiddesignpatterns.com/

**Comment by aritraroy** [comment]
I am adding this site. The only reason because of which I was having second thoughts is that the site is not updated often.

**Comment by alexjlockwood** [comment]
I aim for quality, not quantity. :)

**Comment by aritraroy** [comment]
That's exactly what made me add it to the list. I myself have learned quite a lot from there before.
