### ISSUE TITLE
Suggestion for free animation tools: Android Icon Animator & Shape Shifter

### ISSUE THREAD

**Issue by alexjlockwood** [aritraroy/UltimateAndroidReference#7]
Android Icon Animator (https://romannurik.github.io/AndroidIconAnimator) - useful tool by Roman Nurik that is useful for creating simple AnimatedVectorDrawables

Shape Shifter (https://shapeshifter.design) - useful tool for creating simple path morphing AnimatedVectorDrawables

**Comment by aritraroy** [comment]
This list already has AndroidAssetStudio so anyone can visit AndroidIconAnimator from there. 

I have added Shape Shifter. Thank you. 👍
